import { createApp, h, ref } from 'vue';
import { SortableArea, SortableRoot } from '../../src/vue.js';
import type { AfterDragResult, FrameworkSortableChange } from '../../src/core.js';

type Item = { id: string };
const nestedParent = new URLSearchParams(location.search).has('nested-parent')
  ? { areaId: 'todo', itemId: 'a' } : undefined;
let controls: Record<string, () => void> = {};
let state = () => ({ areas: { todo: [] as string[], done: [] as string[] }, events: [] as string[], lastOperation: null as { operation: string; sourceAreaId: string; destinationAreaId: string; itemId: string; destinationIndex: number } | null, resources: { activeSessions: 0, placeholders: 0 } });

const Fixture = {
  setup() {
    const todo = ref<Item[]>([{ id: 'a' }, { id: 'b' }]); const done = ref<Item[]>([{ id: 'c' }, { id: 'd' }]); const events = ref<string[]>([]); const rejectDone = ref(false); const todoDisabled = ref(false); const showTodo = ref(true); const showDone = ref(true); const showRoot = ref(true); const commitChanges = ref(true); const throwOnChange = ref(false); const todoDirection = ref<'vertical' | 'horizontal'>('vertical'); const doneDirection = ref<'vertical' | 'horizontal'>('vertical'); const doneThreshold = ref<number | undefined>(undefined); const lastOperation = ref<ReturnType<typeof state>['lastOperation']>(null);
    const log = (value: string) => { events.value = [...events.value, value]; };
    const onChange = (change: FrameworkSortableChange<Item>) => { lastOperation.value = { operation: change.operation, sourceAreaId: change.source.areaId, destinationAreaId: change.destination.areaId, itemId: String(change.itemId), destinationIndex: change.destination.index }; if (commitChanges.value) for (const update of change.updates) { if (update.areaId === 'todo') todo.value = [...update.items]; if (update.areaId === 'done') done.value = [...update.items]; } log('change'); if (throwOnChange.value) throw new Error('fixture change error'); };
    const onAfterDrag = (result: AfterDragResult) => log(`after:${result.status}:${result.reason}`);
    controls = { horizontal: () => { todoDirection.value = 'horizontal'; }, emptyGeometry: () => { doneDirection.value = 'horizontal'; doneThreshold.value = 32; done.value = []; }, scrollable: () => { const scroll = document.querySelector<HTMLElement>('[data-test-scroll]'); scroll?.classList.add('scrollable'); if (scroll?.querySelector('[data-test-scroll-spacer]') === null) { const spacer = document.createElement('div'); spacer.setAttribute('data-test-scroll-spacer', ''); scroll?.append(spacer); } scroll?.scrollTo({ top: 100 }); }, outside: () => undefined, escape: () => undefined, 'pointer-cancel': () => [0, 1].forEach((pointerId) => document.dispatchEvent(new PointerEvent('pointercancel', { pointerId, bubbles: true }))), blur: () => window.dispatchEvent(new Event('blur')), disabled: () => { todoDisabled.value = true; }, reject: () => { rejectDone.value = true; }, unmount: () => { showDone.value = false; }, destroy: () => { showRoot.value = false; }, 'callback-error': () => { throwOnChange.value = true; }, 'state-not-committed': () => { commitChanges.value = false; }, remount: () => { showRoot.value = true; showTodo.value = true; showDone.value = true; todoDisabled.value = false; commitChanges.value = true; throwOnChange.value = false; todoDirection.value = 'vertical'; doneDirection.value = 'vertical'; doneThreshold.value = undefined; } };
    state = () => ({ areas: { todo: todo.value.map((item) => item.id), done: done.value.map((item) => item.id) }, events: [...events.value], lastOperation: lastOperation.value, resources: { activeSessions: document.querySelectorAll('[data-comins-sortable-dragging]').length, placeholders: document.querySelectorAll('[data-comins-sortable-placeholder]').length } });
    const renderArea = (areaId: 'todo' | 'done', items: typeof todo, update: (items: readonly Item[]) => void, direction: 'vertical' | 'horizontal', accept?: () => boolean, disabled?: boolean, threshold?: number) => h(SortableArea<Item>, { areaId, parent: areaId === 'done' ? nestedParent : undefined, group: 'fixture', modelValue: items.value, itemKey: 'id', autoScroll: true, direction, emptyInsertThreshold: threshold, accept, disabled, class: { horizontal: direction === 'horizontal', 'zero-primary-axis': direction === 'horizontal' && threshold !== undefined }, 'onUpdate:modelValue': update }, { item: ({ item }: { item: Item }) => h('div', { tabindex: 0, role: 'listitem', 'data-sortable-id': item.id, 'aria-label': `Item ${item.id}`, 'aria-selected': 'false' }, item.id) });
    return () => showRoot.value ? h(SortableRoot<Item>, { onBeforeDragStart: () => log('before'), onDragStart: () => log('start'), onDrag: () => log('drag'), onInsertDragArea: () => log('insert'), onChange, onAfterDrag }, { default: () => [h('div', { 'data-test-scroll': '' }, [h('section', { 'data-area-section': 'todo' }, [h('h2', 'Todo'), h('div', { role: 'list' }, [showTodo.value ? renderArea('todo', todo, (items) => { if (commitChanges.value) todo.value = [...items]; }, todoDirection.value, undefined, todoDisabled.value) : null])]), h('section', { 'data-area-section': 'done' }, [h('h2', 'Done'), h('div', { role: 'list' }, [showDone.value ? renderArea('done', done, (items) => { if (commitChanges.value) done.value = [...items]; }, doneDirection.value, () => !rejectDone.value, undefined, doneThreshold.value) : null])])]), h('button', { type: 'button', 'aria-label': 'Clear done', onClick: () => { done.value = []; } }, 'Clear done'), h('output', { 'data-test-events': '' }, events.value.join(','))] }) : null;
  },
};
const target = document.querySelector('#app'); if (target === null) throw new Error('Missing fixture root'); createApp(Fixture).mount(target);
window.__sortableFixture = { state: () => state(), controls }; Object.defineProperty(window.__sortableFixture, 'controls', { get: () => controls });
